version: 2 # use CircleCI 2.0 #
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b8:df:5d:86:e2:23:77:a5:7d:58:82:6f:e8:b8:50:71"
      - run: ./mvnw clean install
      - run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./gorakulist-client/target/gorakulist-client-0.0.1.jar ${USER}@${RAINBOW_SERVER}:${WORKDIR}/gorakulist-client-0.0.2.jar
workflows:
  version: 2
  build:
    jobs:
      - build