version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '91:76:68:69:af:77:ec:ce:82:62:47:1d:9b:91:ec:2a'
      - run: ./mvnw clean install
      - run: sudo scp ./gorakulist-client/target/gorakulist-client-0.0.1.jar ${USER}@${RAINBOW_SERVER}:${WORKDIR}gorakulist-client-0.0.2.jar
workflows:
  build:
    jobs:
      - build